nav:
  Home: /
  Public speaking: /public-speaking/
  Community events: /community-events/
  Publications: /publications/
#   Blog: /archives/

projects_url: http://github.com/gergelyke

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/gergelyke
        twitter: https://twitter.com/nthgergo
        linkedin: https://www.linkedin.com/in/nthgergo
    show_all_posts: false
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
